palettes:
  Flying Tiger:
    - "#000000"
    - "#ffffff"
    - "#ff0000"
    - "#00ff00"
    - "#0000ff"
    - "#ffff00"
    - "#ffa500"
    - "#800080"
    - "#ff69b4"
    - "#00ffff"

  Black & White:
    - "#000000"
    - "#ffffff"

  Cozy 8:
    - "#2e294e"
    - "#541388"
    - "#f1e9da"
    - "#ffd400"
    - "#d90368"
    - "#0081a7"
    - "#00afb9"
    - "#fed9b7"

  Retro Gaming:
    - "#0f0f23"
    - "#262b44"
    - "#3e4a5c"
    - "#5a6988"
    - "#738699"
    - "#8ea3b0"
    - "#a4c0c7"
    - "#c0dddd"

  Sunset Vibes:
    - "#2d1b69"
    - "#11296b"
    - "#0f4c75"
    - "#3282b8"
    - "#bbe1fa"
    - "#ff6b6b"
    - "#ffa726"
    - "#ffcc02"

  Forest Dreams:
    - "#1a3a2e"
    - "#16423c"
    - "#0f3460"
    - "#533a71"
    - "#6a994e"
    - "#a7c957"
    - "#f2e8cf"
    - "#bc4749"
